### ISSUE TITLE
Infinite loop when there is insecable spaces in literal array

### ISSUE THREAD

**Issue by jecisc** [guillep/pharo-core#12886]
In the latest Pharo 11 image I have a playgroud with some code and comments. If I try to copy (cmd + c) some text, my image locks on what seems to be an infinite loop. 

I found that the problem comes from the fact that I had an array with insecable spaces in it. Apparently it produces a faulty AST but this seems to end up in a loop?

I know @privat is working on that so it might interest you.

The code that produced the problem:

```st

(housing column: #median_income) groupByBins: { 0 . 1.5 . 3 . 4.5 . 6 . Float infinity } labeled: #(1 2 3 4 5).
```

Try to copy paste that in a playground, then do ctrl + a and ctrl + c. Your image will freeze because of the insecable space between the 4 and the 5 in `#(1 2 3 4 5)`

**Comment by privat** [comment]
Not able to reproduce. Could it be UI related?

Can you try with something like the following?

```st
source := '(housing column: #median_income) groupByBins: { 0 . 1.5 . 3 . 4.5 . 6 . Float infinity } labeled: #(1 2 3 4@5).' copy.
source replaceAll: $@ with: (Unicode value: 16rA0 "NO-BREAK SPACE").
Smalltalk compiler noPattern: true; compile: source.
```

**Comment by jecisc** [comment]
In that case I get this:

```
RBParser>>parserError:
RBParser>>parseLiteralArrayObject
RBParser>>parseLiteralArray
RBParser>>parsePrimitiveObject
RBParser>>parseUnaryMessage
RBParser>>parseBinaryMessage
RBParser>>parseKeywordMessageWith:
RBParser>>parseKeywordMessage
RBParser>>parseCascadeMessage
RBParser>>parseAssignment
RBParser>>parseStatementInto:periodList:withAcceptedStatementClosers:
RBParser>>parseStatementList:into:untilAnyCloserOf:
RBParser>>parseStatements:into:untilAnyCloserOf:
RBParser>>parseMethodBodyInto:
RBParser>>parseDoIt
OCReceiverDoItSemanticScope(OCDoItSemanticScope)>>parseASTBy:
[
		parser := self createParser.
		ast := self semanticScope parseASTBy: parser.

		ast methodNode compilationContext: self compilationContext.
		self callParsePlugins.
		self doSemanticAnalysis ] in OpalCompiler>>parse in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
OpalCompiler>>parse
[
		self parse.
		self semanticScope compileMethodFromASTBy: self
	] in OpalCompiler>>compile in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
OpalCompiler>>compile
OpalCompiler>>compile:
UndefinedObject>>DoIt
OCReceiverDoItSemanticScope(OCDoItSemanticScope)>>evaluateDoIt:
OpalCompiler>>evaluate
[
		self announcer announce: (SpCodeWillBeEvaluatedAnnouncement newContent: aString).
		oldBindings := self interactionModel bindings copy.
		receiver := self interactionModel doItReceiver.
		result := receiver class compiler
			source: aString readStream;
			context: self interactionModel doItContext;
			receiver: self interactionModel doItReceiver;
			requestor: self interactionModel;
			environment: self environment;
			failBlock:  [ 
				self announcer announce: (SpCodeEvaluationFailedAnnouncement newContent: aString).
				^ compileErrorBlock value ];
			evaluate.
		oldBindings size = self interactionModel bindings size 
			ifFalse: [ self withAdapterDo: [ :anAdapter | anAdapter refreshStyling ] ].
		self announcer announce: (SpCodeEvaluationSucceedAnnouncement newContent: aString).
		result ] in SpCodePresenter>>evaluate:onCompileError:onError: in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
SpCodePresenter>>evaluate:onCompileError:onError:
SpCodePrintItCommand(SpCodeSelectionCommand)>>evaluate:andDo:
SpCodePrintItCommand(SpCodeSelectionCommand)>>evaluateSelectionAndDo:
SpCodePrintItCommand>>execute
SpCommand(CmCommandDecorator)>>execute
[ self decoratedCommand execute ] in SpToolCurrentApplicationCommand>>execute in Block: [ self decoratedCommand execute ]
[ activeProcess
			psValueAt: index
			put: anObject.
		aBlock value ] in SpToolCurrentApplication(DynamicVariable)>>value:during: in Block: [ activeProcess...
FullBlockClosure(BlockClosure)>>ensure:
SpToolCurrentApplication(DynamicVariable)>>value:during:
SpToolCurrentApplication class(DynamicVariable class)>>value:during:
SpToolCurrentApplicationCommand>>execute
[ self decoratedCommand execute ] in SpToolCurrentApplicationCommand>>execute in Block: [ self decoratedCommand execute ]
[ activeProcess
			psValueAt: index
			put: anObject.
		aBlock value ] in SpToolCurrentApplication(DynamicVariable)>>value:during: in Block: [ activeProcess...
FullBlockClosure(BlockClosure)>>ensure:
SpToolCurrentApplication(DynamicVariable)>>value:during:
SpToolCurrentApplication class(DynamicVariable class)>>value:during:
SpToolCurrentApplicationCommand>>execute
[ 
			aCmCommand canBeExecuted 
				ifTrue: [ aCmCommand execute ] ] in SpKMCategoryBuilder>>visitCommand: in Block: [ ...
FullBlockClosure(BlockClosure)>>cull:
FullBlockClosure(BlockClosure)>>cull:cull:
FullBlockClosure(BlockClosure)>>cull:cull:cull:
KMCategoryBinding>>completeMatch:buffer:
[ :l | l completeMatch: self buffer: aBuffer ] in KMKeymap>>notifyCompleteMatchTo:buffer: in Block: [ :l | l completeMatch: self buffer: aBuffer ]
Array(SequenceableCollection)>>do:
KMKeymap>>notifyCompleteMatchTo:buffer:
KMKeymap>>onMatchWith:notify:andDo:
[ :entry |
		entry onMatchWith: anEventBuffer
			notify: aMatchListener
			andDo: aBlock ] in KMCategory>>onMatchWith:notify:andDo: in Block: [ :entry |...
Set>>do:
KMCategory>>onMatchWith:notify:andDo:
KMCategoryBinding>>verifyMatchWith:notifying:thenDoing:
[ :aTarget |
		"nice hack to stop in the first listener"
		aTarget
			verifyMatchWith: anEventBuffer
			notifying: self
			thenDoing: [ ^self ] ] in KMDispatcher>>dispatch: in Block: [ :aTarget |...
OrderedCollection>>do:
KMDispatcher>>dispatch:
KMTarget>>dispatch:
[ :targetToDispatch |
		targetToDispatch dispatch: KMBuffer uniqueInstance buffer copy.
		aKeyboardEvent wasHandled ifTrue: [ ^self ].
	] in KMDispatchChain>>dispatch: in Block: [ :targetToDispatch |...
KMDispatchChain>>do:
KMDispatchChain>>dispatch:
KMDispatcher>>dispatchKeystroke:
RubEditingArea(Morph)>>dispatchKeystrokeForEvent:
RubEditingArea(Morph)>>handleKeystrokeWithKeymappings:
KMShortcutHandler>>handleKeystroke:inMorph:
RubEditingArea(Morph)>>handleKeyDown:
RubEditingArea(RubAbstractTextArea)>>handleKeyDown:
KeyboardEvent>>sentTo:
RubEditingArea(Morph)>>handleEvent:
RubEditingArea(Morph)>>handleFocusEvent:
[
		result := focusHolder handleFocusEvent: transformedEvent.
	] in HandMorph>>sendFocusEvent:to:clear: in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendKeyboardEvent:
HandMorph>>handleEvent:
[
		(morphicWorld activeHand isNotNil and: [ anEvent hand isNotNil ]) ifTrue: [
			morphicWorld activeHand handleEvent: anEvent
		]
	] in OSWindowMorphicEventHandler>>dispatchMorphicEvent: in Block: [...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycleNow
WorldMorph>>doOneCycle
[
		| extraWorldsToDraw |
		extraWorldsToDraw := ExtraWorldListMutex critical: [
			                     self extraWorldList ].
		extraWorldsToDraw do: [ :world | world doOneCycle ].

		(self currentWorld isNotNil and: [
			 (extraWorldsToDraw includes: self currentWorld) not ]) ifTrue: [
			self currentWorld doOneCycle ] ] in WorldMorph class>>doOneCycle in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
WorldState class>>doDrawCycleWith:
WorldMorph class>>doOneCycle
MorphicRenderLoop>>doOneCycle
MorphicRenderLoop>>doOneCycleWhile:
[ MorphicRenderLoop new doOneCycleWhile: [ true ] ] in MorphicUIManager>>spawnNewProcess in Block: [ MorphicRenderLoop new doOneCycleWhile: [ tru[..]
[self value.
			"IMPORTANT: Do not step over next line of code. See method comments for details"
			Processor terminateRealActive] in FullBlockClosure(BlockClosure)>>newProcess in Block: [self value....

```

**Comment by jecisc** [comment]
I can still reproduce it with the first explanation I gave. 

If I interrupt the process I often end up in a stack like this:

```
Array(Collection)>>ifEmpty:ifNotEmpty:
RBMessageNode(RBProgramNode)>>comments:
RBParser>>addCommentsTo:
[ self addCommentsTo: statements last ] in RBParser>>parseStatementList:into:untilAnyCloserOf: in Block: [ self addCommentsTo: statements last ]
FullBlockClosure(BlockClosure)>>cull:
OrderedCollection(Collection)>>ifEmpty:ifNotEmpty:
RBParser>>parseStatementList:into:untilAnyCloserOf:
RBParser>>parseArray
RBParser>>parsePrimitiveObject
RBParser>>parseUnaryMessage
RBParser>>parseBinaryMessage
RBParser>>parseKeywordMessageWith:
RBParser>>parseKeywordMessage
RBParser>>parseCascadeMessage
RBParser>>parseAssignment
RBParser>>parseStatementInto:periodList:withAcceptedStatementClosers:
RBParser>>parseStatementList:into:untilAnyCloserOf:
RBParser>>parseStatements:into:untilAnyCloserOf:
RBParser>>parseMethodBodyInto:
RBParser>>parseExpression
RBParser class>>parseExpression:onError:
RBParser class>>parseFaultyExpression:
[
		RBParser parseFaultyExpression: self textArea string] in [node := RBParser parseMethod: self textArea string onError: [
		RBParser parseFaultyExpression: self textArea string]
	] in RubSmalltalkEditor>>bestNodeInTextArea in Block: [...
FullBlockClosure(BlockClosure)>>cull:
FullBlockClosure(BlockClosure)>>cull:cull:
FullBlockClosure(BlockClosure)>>cull:cull:cull:
RBParser>>parserError:
RBParser>>parseLiteralArrayObject
RBParser>>parseLiteralArray
RBParser>>parsePrimitiveObject
RBParser>>parseUnaryMessage
RBParser>>parseBinaryMessage
RBParser>>parseKeywordMessageWith:
RBParser>>parseKeywordMessage
RBParser>>parseCascadeMessage
RBParser>>parseAssignment
RBParser>>parseStatementInto:periodList:withAcceptedStatementClosers:
RBParser>>parseStatementList:into:untilAnyCloserOf:
RBParser>>parseStatements:into:untilAnyCloserOf:
RBParser>>parseMethodBodyInto:
RBParser>>parseMethod
[ parser parseMethod ] in RBParser class>>parseMethod:onError: in Block: [ parser parseMethod ]
FullBlockClosure(BlockClosure)>>on:do:
RBParser class>>parseMethod:onError:
[node := RBParser parseMethod: self textArea string onError: [
		RBParser parseFaultyExpression: self textArea string]
	] in RubSmalltalkEditor>>bestNodeInTextArea in Block: [node := RBParser parseMethod: self textArea s[..]
FullBlockClosure(BlockClosure)>>on:do:
RubSmalltalkEditor>>bestNodeInTextArea
RubSmalltalkEditor>>copySelection
SpMorphicCodeAdapter(SpMorphicTextAdapter)>>copyText
[ :anAdapter | anAdapter copyText ] in SpCodePresenter(SpTextPresenter)>>doTextCopy in Block: [ :anAdapter | anAdapter copyText ]
FullBlockClosure(BlockClosure)>>cull:
SpMorphicCodeAdapter(ProtoObject)>>ifNotNil:
SpCodePresenter(SpAbstractPresenter)>>withAdapterDo:
SpCodePresenter(SpTextPresenter)>>doTextCopy
SpTextCopyCommand>>execute
SpCommand(CmCommandDecorator)>>execute
[ self decoratedCommand execute ] in SpToolCurrentApplicationCommand>>execute in Block: [ self decoratedCommand execute ]
[ activeProcess
			psValueAt: index
			put: anObject.
		aBlock value ] in SpToolCurrentApplication(DynamicVariable)>>value:during: in Block: [ activeProcess...
FullBlockClosure(BlockClosure)>>ensure:
SpToolCurrentApplication(DynamicVariable)>>value:during:
SpToolCurrentApplication class(DynamicVariable class)>>value:during:
SpToolCurrentApplicationCommand>>execute
[ 
			aCmCommand canBeExecuted 
				ifTrue: [ aCmCommand execute ] ] in SpKMCategoryBuilder>>visitCommand: in Block: [ ...
FullBlockClosure(BlockClosure)>>cull:
FullBlockClosure(BlockClosure)>>cull:cull:
FullBlockClosure(BlockClosure)>>cull:cull:cull:
KMCategoryBinding>>completeMatch:buffer:
[ :l | l completeMatch: self buffer: aBuffer ] in KMKeymap>>notifyCompleteMatchTo:buffer: in Block: [ :l | l completeMatch: self buffer: aBuffer ]
Array(SequenceableCollection)>>do:
KMKeymap>>notifyCompleteMatchTo:buffer:
KMKeymap>>onMatchWith:notify:andDo:
[ :entry |
		entry onMatchWith: anEventBuffer
			notify: aMatchListener
			andDo: aBlock ] in KMCategory>>onMatchWith:notify:andDo: in Block: [ :entry |...
Set>>do:
KMCategory>>onMatchWith:notify:andDo:
KMCategoryBinding>>verifyMatchWith:notifying:thenDoing:
[ :aTarget |
		"nice hack to stop in the first listener"
		aTarget
			verifyMatchWith: anEventBuffer
			notifying: self
			thenDoing: [ ^self ] ] in KMDispatcher>>dispatch: in Block: [ :aTarget |...
OrderedCollection>>do:
KMDispatcher>>dispatch:
KMTarget>>dispatch:
[ :targetToDispatch |
		targetToDispatch dispatch: KMBuffer uniqueInstance buffer copy.
		aKeyboardEvent wasHandled ifTrue: [ ^self ].
	] in KMDispatchChain>>dispatch: in Block: [ :targetToDispatch |...
KMDispatchChain>>do:
KMDispatchChain>>dispatch:
KMDispatcher>>dispatchKeystroke:
RubEditingArea(Morph)>>dispatchKeystrokeForEvent:
RubEditingArea(Morph)>>handleKeystrokeWithKeymappings:
KMShortcutHandler>>handleKeystroke:inMorph:
RubEditingArea(Morph)>>handleKeyDown:
RubEditingArea(RubAbstractTextArea)>>handleKeyDown:
KeyboardEvent>>sentTo:
RubEditingArea(Morph)>>handleEvent:
RubEditingArea(Morph)>>handleFocusEvent:
[
		result := focusHolder handleFocusEvent: transformedEvent.
	] in HandMorph>>sendFocusEvent:to:clear: in Block: [...
FullBlockClosure(BlockClosure)>>on:do:
WorldMorph>>becomeActiveDuring:
HandMorph>>sendFocusEvent:to:clear:
HandMorph>>sendEvent:focus:clear:
HandMorph>>sendKeyboardEvent:
HandMorph>>handleEvent:
[
		(morphicWorld activeHand isNotNil and: [ anEvent hand isNotNil ]) ifTrue: [
			morphicWorld activeHand handleEvent: anEvent
		]
	] in OSWindowMorphicEventHandler>>dispatchMorphicEvent: in Block: [...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleFor:
WorldMorph>>doOneCycleNow
WorldMorph>>doOneCycle
[
		| extraWorldsToDraw |
		extraWorldsToDraw := ExtraWorldListMutex critical: [
			                     self extraWorldList ].
		extraWorldsToDraw do: [ :world | world doOneCycle ].

		(self currentWorld isNotNil and: [
			 (extraWorldsToDraw includes: self currentWorld) not ]) ifTrue: [
			self currentWorld doOneCycle ] ] in WorldMorph class>>doOneCycle in Block: [...
FullBlockClosure(BlockClosure)>>ensure:
WorldState class>>doDrawCycleWith:
WorldMorph class>>doOneCycle
MorphicRenderLoop>>doOneCycle
MorphicRenderLoop>>doOneCycleWhile:
[ MorphicRenderLoop new doOneCycleWhile: [ true ] ] in MorphicUIManager>>spawnNewProcess in Block: [ MorphicRenderLoop new doOneCycleWhile: [ tru[..]
[self value.
			"IMPORTANT: Do not step over next line of code. See method comments for details"
			Processor terminateRealActive] in FullBlockClosure(BlockClosure)>>newProcess in Block: [self value....
```

**Comment by MarcusDenker** [comment]
is this fixed by https://github.com/pharo-project/pharo/pull/12891 ?

**Comment by privat** [comment]
I still cannot reproduce on my machine. But the bug seems real and related to parsing. Or to something that calls parsing.
The first stack trace feel normal.
The second also, but if something is looping, it won't appears. (And we don't have stacktraces with counters... Maybe profiling information can show the looper culprits?)

#12891 checked that nothing special is done with nbsp, it is considered as a random unknown Unicode character like `¿` or `🐱`

Maybe the nbsp is unrelated and there is something else? @jecisc can you try to reduce the string into a minimum one? Can you also give the asArray of it so we can see if there is other weirdness?

**Comment by jecisc** [comment]
This still happens in the latest Pharo. 

I tried to copy paste the string I provided here but it does not happens when I do that. I need to introduce the insecable space myself with Shift + space in order to reproduce it. 

There is something weird also is that the character that gets added when I do that has a code point of 8239 and not 160 like I would expect for an no break space.

I could produce the problem with:

```st
#(1 2)
```

where the space is `8239 asCharacter`

If I do "asArray" I get a Unknown character error

**Comment by jecisc** [comment]
```st
source := '#(1@2)' copy.
source replaceAll: $@ with: 8239 asCharacter.
Smalltalk compiler noPattern: true; compile: source.
```

Produces the unkwonw character error

**Comment by jecisc** [comment]
Here is a way to reproduce it:

```st
string := '#(1 2 3@4 5)'.
string := string copyReplaceAll: '@' with: (8239 asCharacter) asString.

RBParser parseMethod:  string onError: [ RBParser parseFaultyExpression: string ]
```

**Comment by jecisc** [comment]
The problem seems to come from `RBParser>>#parseLiteralArrayObject` because we never step in case we end up in a parsing error

**Comment by privat** [comment]
Nice! I can now loop infinitely!

I will investigate. With a fast glance, it could be related to `onError`.

The `onError:` (and the whole `errorBlock`) API is weird because it serves three concerns.

1. as a fail block to stop parsing in case or error, but clients should not forget to put a ^ to leave
2. as a notification block to do unrelated things, but the clients should return nil as the value of the block
3. as a recovery mechanism to provide alternative node, but this client should advance (like in consuming the problematic token). This is a clear breach of encapsulation.  If not, the next token will be equally faulty (thus infinite loop because tokens are not consumed). Note: we cannot consume tokens by default because what happen most of the time are unfinished grammatical construction, ie. the token is unexpected, but because a dot or a closing `)` is missing, therefore throwing away the next token is not a good solution.

I tried to kill the API in #12912 but without so much success yet. I try all things, I achieve what I can :)

So, to fix your hypothetical example, the alternatives are

1. `RBParser parseMethod:  string onError: [ ^ RBParser parseFaultyExpression: string ]`  and your caller get the faulty expression.
2. `RBParser parseMethod:  string onError: [ RBParser parseFaultyExpression: string. nil ]` and default error mecanism takes pace (buggy syntax error recovery). Not that here the faulty parsing is done for nothing.
3. `RBParser parseMethod:  string onError: [ :msg :loc :parser | parser step. RBParser parseFaultyExpression: string ]` and the faulty element will be replaced with a nested faulty thing, or something. I'm not even sure what the behavior here.

The correct way night be simply `RBParser parseFaultyExpression: string` without the non-faulty parsing.

OK, all this does not explain the initial issue. Something might be using a bad error block in the call chain.
It does not explain either why 8239 among all characters, so maybe my hypothesis are completely off.

**Comment by privat** [comment]
Damn, you already provided a fix. you're fast.

**Comment by jecisc** [comment]
I was about to write that I proposed something before seen your answer ahah
But I'd love your review since the parser is not a part of the system I know well :)

**Comment by jecisc** [comment]
I agree that the #onError: is missleading. I was confused while looking at the senders and seen how they had different way to handle things.
I could have fixed my issue just with a return, but to me that was just pushing the dust under the carpet.

**Comment by privat** [comment]
By the way, a simpler way to reproduce is to write `#(¿)` (or `#(¨)` if you don't have a Spanish keyboard or a compose key) in the playground, then copy (Ctrl-C). No even need to select anything.

I'm still not sure why `#()` is looping and not the other syntactic construction I tried...
