### ISSUE TITLE
[CI] Pharo 13 test failing: RSDependencyTest>>testDependencies

### ISSUE THREAD

**Issue by MarcusDenker** [guillep/pharo-core#16568]
**Bug description**
RSDependencyTest>>testDependencies is failing on the CI:

```
MessageNotUnderstood
Message not understood: Package >> #dependentPackages
Package(Object)>>doesNotUnderstand: #dependentPackages
RSDependencyTest>>assertPackage:doesNotDependOn:
RSDependencyTest>>testDependencies
RSDependencyTest(TestCase)>>performTest
```

**Comment by pavel-krivanek** [comment]
I already fixed it, needs to be integrated

https://github.com/pharo-graphics/Roassal/pull/63

**Comment by MarcusDenker** [comment]
Somehow I do not have the right to merge the PR there

**Comment by pavel-krivanek** [comment]
Ups, that is a problem for a package which is a default Pharo component ;-)
Please, ask Alex or Milton for permissions

**Comment by MarcusDenker** [comment]
As long as this issue is not fixe, all PRs submitted for Pharo13 will fail the CI check

**Comment by jecisc** [comment]
I added Marcus as an admin of roassal and I merged the PR. There is a new release v1.06d we can use to fix the test.

**Comment by MarcusDenker** [comment]
I re-open as the merged code does not end up in Pharo 13, test still fails

**Comment by jecisc** [comment]
We need to update the used releases of roassal
