### ISSUE TITLE
Code completion will intermingle code completion with following, non-selected characters if no blank

### ISSUE THREAD

**Issue by ericwinger** [guillep/pharo-core#16796]
**Bug description**
Code completion will complete with completion characters intermixed with following, non-selected characters if there is no blank before the existing characters. 

**To Reproduce**

1. In a virgin image, open a source editor or a playground, highlight some text with a non-blank character immediately trailing the selection. 
![image](https://github.com/pharo-project/pharo/assets/36212516/89d251e8-c063-4590-ad4e-77ff8433f553)

2. Start typing new characters replacing the old characters until a code completion pop-up appears. 
![image](https://github.com/pharo-project/pharo/assets/36212516/e074a0a0-c3dc-49c2-b0f0-4bff30746e75)

3. Choose the first code completion option. 
4. Result is intermingled text
![image](https://github.com/pharo-project/pharo/assets/36212516/88bd92d4-e6e7-4e32-9acf-c1f59eabef3c)

**Expected behavior**
Code completion behavior should not intermingle the code completion and the existing characters. 

**Screenshots**
See above

**Version information:**

Pharo 11.0.0
Build information: Pharo-11.0.0+build.714.sha.0ead11d0b8573ff685db8a39fceeca2a8d528d3e (64 Bit)

**Expected development cost**

- It may be worth searching open code completion issues for a duplicate. I searched but couldn't find an exact match. 
- Costs include duplicated effort retyping code often for the user. 
- Other costs unknown. 

**Additional context**
Code completion is pretty handy, but this bug slows down development. 
`NECPreferences spaceAfterCompletion` = true in the above example
There seem to be some problems in this method: `CompletionEngine>>#replaceTokenInEditorWith:` such as:
- `self editor selectInvisiblyFrom: wordStart to: wordEnd - 1.` does make a visible selection
- which appears to impact the following statement: `old := self editor selection.`

I didn't investigate further.

**Comment by jecisc** [comment]
Hi, 
Pharo code completion has been improved in Pharo 12. I think what you reported has been fixed. Could you check if everything work right in P12 or 13?

**Comment by ericwinger** [comment]
Thanks for responding so quickly! 

The behavior is different in Pharo 12, but it is still not correct. Now the following character(s?) are replaced. Here's an example. 

1. Select text up to colon
![image](https://github.com/pharo-project/pharo/assets/36212516/76a7ab14-867f-4850-aa38-1236ceea94fa)
2. Type until auto complete. See snazzy new behavior dialog. Choose selection.  
![image](https://github.com/pharo-project/pharo/assets/36212516/5a780744-a33f-4010-88bb-bd40fae9ae8a)
3. Replaces following colon
![image](https://github.com/pharo-project/pharo/assets/36212516/9dd6df7c-0b00-42df-a091-54ec106a19db)

```
Pharo 12.0.0
Build information: Pharo-12.0.0+SNAPSHOT.build.1516.sha.25ecf718d4a363b275862b4a093b1a240ec7e8d2 (64 Bit)
```
