### ISSUE TITLE
Class comments not available anymore in Calypso

### ISSUE THREAD

**Issue by hernanmd** [guillep/pharo-core#17348]
**To Reproduce**
1. Open Calypso Browser
2. Click on any class
3. Click on the comment tab

<img width="1122" alt="Screenshot 2024-11-06 at 22 33 16" src="https://github.com/user-attachments/assets/fb5906d2-ce67-4ed6-adc4-f30673e64755">

**Comment by Ducasse** [comment]
We know the problem. This is because the extensions of beautiful comments got lost.

**Comment by jecisc** [comment]
The missing extension should be fixed now. If it does not work still, it might be another problem?

**Comment by hernanmd** [comment]
Problem is still there in the latest build:

<img width="1203" alt="Screenshot 2024-11-15 at 12 19 46" src="https://github.com/user-attachments/assets/4fe1277f-903e-41c3-95f5-ae80887eb6e8">

**Comment by astares** [comment]
Can confirm

**Comment by Ducasse** [comment]
I found the problem. The method extension on class was lost. 

```
Class >> buildMicroDownUsing: aBuilder withComment: aString
	
	aBuilder 
		header: [ aBuilder text: 'Class: '.
					aBuilder text: self name ] withLevel: 1;
		horizontalLine;
		text: aString.
	
	self addDocumentSectionExampleCodeTo: aBuilder.
	
	self 
		addDocumentSectionTo: aBuilder  
		label: 'Examples' 
		methods: (self class methods select: [ :each | each protocol = self documentExamplesProtocol ])
```

**Comment by Ducasse** [comment]
I pushed a fix to Microdown branch pharo13 so we will be able to see that after the integration of a  new PR.

**Comment by Ducasse** [comment]
Fixed. 
![Capture 2024-12-02 at 11 01 04](https://github.com/user-attachments/assets/2b6757cf-96ba-446b-a26f-33f68c39057c)
