### ISSUE TITLE
[ICEBERG]The merge preview is not well sized to click on the button

### ISSUE THREAD

**Issue by VincentBlondeau** [guillep/pharo-core#2967]
Sorry about opening bugs reports but....
![image](https://user-images.githubusercontent.com/4706329/54777835-7acf3400-4c13-11e9-90af-0f3697927460.png)

**Comment by VincentBlondeau** [comment]
Fixed

**Comment by bouraqadi** [comment]
This issue does still exist in Pharo 
![icebergMergeButtonHidden](https://user-images.githubusercontent.com/435343/154310048-ee9f5c06-1dc1-48a1-ada1-a2328292f611.jpg)

**Comment by VincentBlondeau** [comment]
indeed: the button should stick to the right side:
<img width="362" alt="CleanShot 2022-03-03 at 09 44 17@2x" src="https://user-images.githubusercontent.com/4706329/156528795-faee82fb-09f8-4a5c-9ecd-1d325a956219.png">

**Comment by MarcusDenker** [comment]
This was fixed
