### ISSUE TITLE
Impossible to add a protocol when the class is empty

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#3364]
We cannot get any menu.
![Screen Shot 2019-05-16 at 22 27 55](https://user-images.githubusercontent.com/432549/57884868-f7ece300-7829-11e9-8773-ded8becbb0e1.png)

We are forced to add a method and only then the protocol appears!!!

**Comment by dionisiydk** [comment]
Do you mean that context menu can't be opened?

Probably it's related to some  table morph changes. Now it does not open
context menu using click on empty space.
I checked Pharo7 and it works fine.

чт, 16 мая 2019 г. в 21:28, StéphaneDucasse <notifications@github.com>:

**Comment by dionisiydk** [comment]
Seems empty space in table does not handle clicks at all. It does not reset
selection for example

чт, 16 мая 2019 г. в 21:56, Denis Kudriashov <dionisiydk@gmail.com>:

**Comment by dionisiydk** [comment]
You can check empty space click using FTExamples
class>>#exampleTreeWithAllItemsFilter in Pharo 8 and Pharo 7.


чт, 16 мая 2019 г. в 21:57, Denis Kudriashov <dionisiydk@gmail.com>:

**Comment by 570gina** [comment]
I can click on the "instance side" to get the menu. (in Pharo 8)
![image](https://user-images.githubusercontent.com/24423847/57934115-38e30700-78bf-11e9-8b22-c93e611a8a44.png)

**Comment by Ducasse** [comment]
This is super strange to have to click on an element to be able to create one.

**Comment by dionisiydk** [comment]
Yes, it is fast table issue introduce in Pharo 8

**Comment by Ducasse** [comment]
Esteban can we have a menu on an empty list?

**Comment by MarcusDenker** [comment]
This has been fixed, I can get a meny for an empty class

**Comment by dionisiydk** [comment]
It still does not work for me.
The problem was with the changes in table morph. The empty area now does not respond to events. But the area under the rows do respond.

**Comment by dionisiydk** [comment]
> You can check empty space click using FTExamples class>>#exampleTreeWithAllItemsFilter in Pharo 8 and Pharo 7.

This is an example out of calypso context

**Comment by guillep** [comment]
I confirm this issue has been solved in version  Pharo-11.0.0+build.481.sha.ca3b1f5a5c2b1b56ff5258e143841a971b5c2686 (64 Bit)
