### ISSUE TITLE
[Linux 64bit] Pharo 8 Devel libgit2_init problem

### ISSUE THREAD

**Issue by C0ldS0b3r** [guillep/pharo-core#4463]
Hello;
On new Pharo launcher download on a 64 bit linux version and ```lib64git2``` (version28) and ```lib64git2-devel``` installed I get the error bellow with the Pharo 8 development VM image.
[![View on vgy.me](https://i.vgy.me/i2sYoS.png "View i2sYoS.png on vgy.me")](https://vgy.me/u/i2sYoS)

**Comment by masukomi** [comment]
This bug still exists 

* 8.0 stable 64 bit
* macOS Catalina (10.15.2)
* even if you have libgit2 installed (`brew install libgit2` )

Note that a new smalltalk user checking out Pharo 8 will have this error be their first smalltalk experience.


```
"<cdecl: long 'git_libgit2_init' () module: '/Users/masukomi/Documents/Pharo/vms/80-x64/Pharo.app/Contents/MacOS/Plugins/libgit2.dylib'>"
self
```

**Comment by Ducasse** [comment]
Thanks for the report. We will have a look.

**Comment by masukomi** [comment]
I'm happy to poke anything that'd give you more info, but i honestly haven't touched Smalltalk in over a decade and would require very newb level instructions. ;)

**Comment by Ducasse** [comment]
:) it can come back super fast. Did you check http://mooc.pharo.org?
This is super strange because most of the Pharoers are on mac and use massively git. 
Can you describe what you did step by step?
Tx

<blockquote><div><strong><a href="http://mooc.pharo.org/">Pharo MOOC: Live Object Programming in Pharo</a></strong></div></blockquote>

**Comment by reugalabf** [comment]
I have the same problem with Pharo 8 (builds 1124 & 1127). 
I have Archlinux 
Linux  5.4.15-arch1-1 #1 SMP PREEMPT Sun, 26 Jan 2020 09:48:50 +0000 x86_64 GNU/Linux

I opened an 1124 image from the terminal. Although the debugger complains about libgit2 not found, the message on the terminal complains about libgit2.so being too short 
"ioLoadModule(//home/fede/Pharo/vms/80-x64/lib/pharo/5.0-201902062351/libgit2.so):
  //home/fede/Pharo/vms/80-x64/lib/pharo/5.0-201902062351/libgit2.so: file too short
External module not found
" 
There is also a similar message (on the Terminal) for libSDL
"ioLoadModule(/home/fede/Pharo/vms/80-x64/lib/pharo/5.0-201902062351/libSDL2.so):
  /home/fede/Pharo/vms/80-x64/lib/pharo/5.0-201902062351/libSDL2.so: file too short
ioLoadModule(/home/fede/Pharo/vms/80-x64/lib/pharo/5.0-201902062351/libSDL2.so):
  /home/fede/Pharo/vms/80-x64/lib/pharo/5.0-201902062351/libSDL2.so: file too short
"

**Comment by Ducasse** [comment]
Thanks fede. We will have a look after the fosdem.

**Comment by masukomi** [comment]
>  Can you describe what you did step by step? - @Ducasse 

1. Open pharo launcher
2. Right click on Pharo 8.0 64 bit under "official distribitions"
3. Choose "Create Image" 
4. Right click on new image
5. Choose "Launch" 

That's it. 

as soon as it launches the error is displayed as seen in the original screenshot.

Once the image is created if I don't modify it before closing it will always happen when I launch it.

**Comment by lokedhs** [comment]
Happens to me on Pharo 9 on Fedora. The interesting thing is that pharo-launcher game me this error as soon as I started it, but it disappeared after I installed the `libgit2-devel` package. However, once I actually start the image, the error still happens.

**Comment by Ducasse** [comment]
We will discuss and see what to do with Christophe.

**Comment by a12l** [comment]
**Disclaimer:** English is not my native language; please excuse typing errors.

I'm experiencing similar problems as the previous posters. I did some more detailed testing to get more precise data for bug triage.

**TL;DR:** The problems occur on _Fedora 31_ but not on _Ubuntu 19.10_. They were both released in October last year within a two-week window.

My machine – there I first experienced the problem – runs Fedora 31 with KDE Plasma installed using the networked installer. The kernel is version `5.5.8-200.fc31.x86_64`.

The hardware that the system runs on an old Thinkpad X230 with

* 4 × Intel® Core™ i5-3320M CPU @ 2.60GHz;
* 15.5 GiB of RAM; and a
* 240 GB SSD connected via SATA 6 Gb/s.

The system isn't easily reproducible, so I did two clean installs of Fedora Workstation 31 (the Fedora project's "main" distribution) and Ubuntu 19.10 (Canonical's latest version of the standard Ubuntu desktop) in two different virtual machines. Fedora 31 was released on 29th October 2019, and Ubuntu 19.10 was released on 17th October 2019.

The virtual machines were created with Libvirt using KVM. The machines were created and are being administrated using virt-manager (Virtual Machine Manager).

To set up the Fedora 31 environment I

1. downloaded the *Fedora Workstation version 31* ISO image from the official website[0];
2. downloaded the checksum file with the hashes[1] for the ISO image downloaded in the previous step;
3. verified the checksum file and the ISO image according to the instructions documented on the download site[2];
4. installed Fedora in the virtual machine;
5. started the virtual machine and connected to it;
6. updated the system by executing the command `sudo dnf update`; and finally
7. installed the package `unzip` by running the command `sudo dnf install unzip`.

After that I

1. downloaded *PharoLauncher-linux-1.9.2-x64.zip*[3] into the directory `/home/pharo/Downloads`;
2. extracted the zip-file with the command `unzip PharoLauncher-linux-1.9.2-x64.zip -d ~/`;
3. went into the directory `/home/pharo/pharolauncher/` and started Pharo Launcher by executing the command `./pharo-launcher`; and here
4. I ran into the problem.

**Disclaimer:

** The pictures were taken after I had installed and uninstalled the package `libgit2-devel`. I'm assuming that the error message is identical after I uninstalled the package as to what it was before I installed the package.

The window that is displayed is shown in figure 1.

![Figure1](https://user-images.githubusercontent.com/38804798/76479749-2406cf80-640d-11ea-8737-7909900080d2.png)

The maximized window with the error message is shown in figure 2.

![Figure2](https://user-images.githubusercontent.com/38804798/76479751-2537fc80-640d-11ea-9a7d-e8b63a1f8471.png)

The output in the terminal -- there I started the Pharo Launcher -- was


```
pthread_setschedparam failed: Operation not permitted
This VM uses a separate heartbeat thread to update its internal clock
and handle events.  For best operation, this thread should run at a
higher priority, however the VM was unable to change the priority.  The
effect is that heavily loaded systems may experience some latency
issues.  If this occurs, please create the appropriate configuration
file in /etc/security/limits.d/ as shown below:

cat <<END | sudo tee /etc/security/limits.d/pharo.conf
*      hard    rtprio  2
*      soft    rtprio  2
END

and report to the pharo mailing list whether this improves behaviour.

You will need to log out and log back in for the limits to take effect.
For more information please see
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/r3732#linux
ioLoadModule(/home/pharo/pharolauncher/pharo-vm/lib/pharo/5.0-201901051900/libgit2.so):
  libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
tryLoading(/home/pharo/pharolauncher/pharo-vm/lib/pharo/5.0-201901051900/libgit2.so/.libs/,libgit2.so): stat(/home/pharo/pharolauncher/pharo-vm/lib/pharo/5.0-201901051900/libgit2.so/.libs/) Not a directory
External module not found
ExternalLibraryFunction(Object)>>error:
ExternalLibraryFunction(Object)>>externalCallFailed
ExternalLibraryFunction(ExternalFunction)>>invokeWithArguments:
LGitLibrary>>libgit2_init
FFICalloutAPI>>function:module:
LGitLibrary(Object)>>ffiCall:
LGitLibrary>>libgit2_init
[ self libgit2_init.
self recordInitializationSuccess ] in LGitLibrary>>initializeLibGit2 in Block: [ self libgit2_init....
BlockClosure>>on:do:
LGitLibrary>>initializeLibGit2
LGitLibrary class>>startUp:
ClassSessionHandler>>startup:
[ :each | each startup: isImageStarting ] in WorkingSession>>runStartup: in Block: [ :each | each startup: isImageStarting ]
[ aBlock value: each ] in [ :each | 
[ aBlock value: each ]
	on: Exception
	do: [ :error | self errorHandler handleError: error ] ] in WorkingSession>>runList:do: in Block: [ aBlock value: each ]
BlockClosure>>on:do:
[ :each | 
[ aBlock value: each ]
	on: Exception
	do: [ :error | self errorHandler handleError: error ] ] in WorkingSession>>runList:do: in Block: [ :each | ...
Array(SequenceableCollection)>>do:
WorkingSession>>runList:do:
WorkingSession>>runStartup:
WorkingSession>>start:
SessionManager>>launchSnapshot:andQuit:
[ isImageStarting := self launchSnapshot: save andQuit: quit.
wait signal ] in SessionManager>>snapshot:andQuit: in Block: [ isImageStarting := self launchSnapshot: save and...etc...
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess in Block: [ self value....
Error: External module not found
ExternalLibraryFunction(Object)>>error:
ExternalLibraryFunction(Object)>>externalCallFailed
ExternalLibraryFunction(ExternalFunction)>>invokeWithArguments:
LGitLibrary>>libgit2_init
FFICalloutAPI>>function:module:
LGitLibrary(Object)>>ffiCall:
LGitLibrary>>libgit2_init
[ self libgit2_init.
self recordInitializationSuccess ] in LGitLibrary>>initializeLibGit2 in Block: [ self libgit2_init....
BlockClosure>>on:do:
LGitLibrary>>initializeLibGit2
LGitLibrary class>>startUp:
ClassSessionHandler>>startup:
[ :each | each startup: isImageStarting ] in WorkingSession>>runStartup: in Block: [ :each | each startup: isImageStarting ]
[ aBlock value: each ] in [ :each | 
[ aBlock value: each ]
	on: Exception
	do: [ :error | self errorHandler handleError: error ] ] in WorkingSession>>runList:do: in Block: [ aBlock value: each ]
BlockClosure>>on:do:
[ :each | 
[ aBlock value: each ]
	on: Exception
	do: [ :error | self errorHandler handleError: error ] ] in WorkingSession>>runList:do: in Block: [ :each | ...
Array(SequenceableCollection)>>do:
WorkingSession>>runList:do:
WorkingSession>>runStartup:
WorkingSession>>start:
SessionManager>>launchSnapshot:andQuit:
[ isImageStarting := self launchSnapshot: save andQuit: quit.
wait signal ] in SessionManager>>snapshot:andQuit: in Block: [ isImageStarting := self launchSnapshot: save and...etc...
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess in Block: [ self value....
```

Sometime around here I downloaded the Pharo 8.0 VM image using the launcher by clicking on the `X` in the upperleft corner in the window displaying the error message and double-clicking on the image in the list in the browsing window to the left in the launcher. When I started the virtual machine I encountered some form of debugging window. I missed taking a screenshot of this error message at the time. I think that it's the same window shown in figure 3, but I'm not one hundred percent sure.

![Figure3](https://user-images.githubusercontent.com/38804798/76479755-25d09300-640d-11ea-9188-4d93ef0dc2c7.png)

I exited the Pharo launcher and installed the `libgit2-devel` package after reading @lokedhs' note "[...] but it disappeared after I installed the libgit2-devel package." The error message shown in figure 1 and figure 2 didn't show up after starting Pharo Launcher again. The output in the terminal was

```
pthread_setschedparam failed: Operation not permitted
This VM uses a separate heartbeat thread to update its internal clock
and handle events.  For best operation, this thread should run at a
higher priority, however the VM was unable to change the priority.  The
effect is that heavily loaded systems may experience some latency
issues.  If this occurs, please create the appropriate configuration
file in /etc/security/limits.d/ as shown below:

cat <<END | sudo tee /etc/security/limits.d/pharo.conf
*      hard    rtprio  2
*      soft    rtprio  2
END

and report to the pharo mailing list whether this improves behaviour.

You will need to log out and log back in for the limits to take effect.
For more information please see
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/r3732#linux
ioLoadModule(/home/pharo/pharolauncher/pharo-vm/lib/pharo/5.0-201901051900/libgit2.so):
  libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
```

But an error message is shown when I open the virtual machine. There was some additional output in the terminal that was


```
pthread_setschedparam failed: Operation not permitted
This VM uses a separate heartbeat thread to update its internal clock
and handle events.  For best operation, this thread should run at a
higher priority, however the VM was unable to change the priority.  The
effect is that heavily loaded systems may experience some latency
issues.  If this occurs, please create the appropriate configuration
file in /etc/security/limits.d/ as shown below:

cat <<END | sudo tee /etc/security/limits.d/pharo.conf
*      hard    rtprio  2
*      soft    rtprio  2
END

and report to the pharo mailing list whether this improves behaviour.

You will need to log out and log back in for the limits to take effect.
For more information please see
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/r3732#linux
ioLoadModule(/home/pharo/pharolauncher/pharo-vm/lib/pharo/5.0-201901051900/libgit2.so):
  libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
UnZip 6.00 of 20 April 2009, by Info-ZIP.  Maintained by C. Spieler.  Send
bug reports using http://www.info-zip.org/zip-bug.html; see README for details.

Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]
  Default action is to extract files in list, except those in xlist, to exdir;
  file[.zip] may be a wildcard.  -Z => ZipInfo mode ("unzip -Z" for usage).

  -p  extract files to pipe, no messages     -l  list files (short format)
  -f  freshen existing files, create none    -t  test compressed archive data
  -u  update files, create if necessary      -z  display archive comment only
  -v  list verbosely/show version info       -T  timestamp archive to latest
  -x  exclude files that follow (in xlist)   -d  extract files into exdir
modifiers:
  -n  never overwrite existing files         -q  quiet mode (-qq => quieter)
  -o  overwrite files WITHOUT prompting      -a  auto-convert any text files
  -j  junk paths (do not make directories)   -aa treat ALL files as text
  -U  use escapes for all non-ASCII Unicode  -UU ignore any Unicode fields
  -C  match filenames case-insensitively     -L  make (some) names lowercase
  -X  restore UID/GID info                   -V  retain VMS version numbers
  -K  keep setuid/setgid/tacky permissions   -M  pipe through "more" pager
  -O CHARSET  specify a character encoding for DOS, Windows and OS/2 archives
  -I CHARSET  specify a character encoding for UNIX and other archives

See "unzip -hh" or unzip.txt for more help.  Examples:
  unzip data1 -x joe   => extract all files except joe from zipfile data1.zip
  unzip -p foo | more  => send contents of foo.zip via pipe into program more
  unzip -fo foo ReadMe => quietly replace existing ReadMe if archive file newer
Archive:  /home/pharo/Pharo/vms/80-x64.zip
   creating: /home/pharo/Pharo/vms/80-x64/bin/
  inflating: /home/pharo/Pharo/vms/80-x64/bin/pharo  
   creating: /home/pharo/Pharo/vms/80-x64/lib/
   creating: /home/pharo/Pharo/vms/80-x64/lib/pharo/
   creating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/AioPlugin.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/AioPlugin.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/B3DAcceleratorPlugin.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/B3DAcceleratorPlugin.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/EventsHandlerPlugin.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/EventsHandlerPlugin.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/FileAttributesPlugin.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/FileAttributesPlugin.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/InternetConfigPlugin.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/InternetConfigPlugin.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/JPEGReadWriter2Plugin.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/JPEGReadWriter2Plugin.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/JPEGReaderPlugin.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/JPEGReaderPlugin.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/RePlugin.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/RePlugin.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/SqueakSSL.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/SqueakSSL.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/SurfacePlugin.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/SurfacePlugin.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libSDL2-2.0.so.0  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libSDL2-2.0.so.0.7.0  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libSDL2.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libcrypto.so.1.0.0  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so.0.25.1  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so.25  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libssh2.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libssh2.so.1  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libssh2.so.1.0.1  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libssl.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libssl.so.1.0.0  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/pharo  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-display-X11.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-display-X11.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-display-fbdev.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-display-fbdev.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-display-null.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-display-null.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-sound-ALSA.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-sound-ALSA.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-sound-NAS.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-sound-NAS.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-sound-OSS.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-sound-OSS.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-sound-null.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-sound-null.so  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-sound-pulse.a  
  inflating: /home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/vm-sound-pulse.so  
  inflating: /home/pharo/Pharo/vms/80-x64/pharo  
pthread_setschedparam failed: Operation not permitted
This VM uses a separate heartbeat thread to update its internal clock
and handle events.  For best operation, this thread should run at a
higher priority, however the VM was unable to change the priority.  The
effect is that heavily loaded systems may experience some latency
issues.  If this occurs, please create the appropriate configuration
file in /etc/security/limits.d/ as shown below:

cat <<END | sudo tee /etc/security/limits.d/pharo.conf
*      hard    rtprio  2
*      soft    rtprio  2
END

and report to the pharo mailing list whether this improves behaviour.

You will need to log out and log back in for the limits to take effect.
For more information please see
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/r3732#linux
ioLoadModule(//home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so):
  libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
ioLoadModule(//home/pharo/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so):
  libcurl-gnutls.so.4: cannot open shared object file: No such file or directory
External module not found
ExternalLibraryFunction(Object)>>error:
ExternalLibraryFunction(Object)>>externalCallFailed
ExternalLibraryFunction(ExternalFunction)>>invokeWithArguments:
LGitLibrary>>libgit2_init
FFICalloutAPI>>function:library:
LGitLibrary(Object)>>ffiCall:library:options:
LGitLibrary(Object)>>ffiCall:library:
LGitLibrary(Object)>>ffiCall:
LGitLibrary>>libgit2_init
[ self libgit2_init.
self recordInitializationSuccess ] in LGitLibrary>>initializeLibGit2 in Block: [ self libgit2_init....
BlockClosure>>on:do:
LGitLibrary>>initializeLibGit2
LGitLibrary class>>startUp:
ClassSessionHandler>>startup:
[ :each | each startup: isImageStarting ] in WorkingSession>>runStartup: in Block: [ :each | each startup: isImageStarting ]
[ aBlock value: each ] in [ :each | 
[ aBlock value: each ]
	on: Exception
	do: [ :error | self errorHandler handleError: error ] ] in WorkingSession>>runList:do: in Block: [ aBlock value: each ]
BlockClosure>>on:do:
[ :each | 
[ aBlock value: each ]
	on: Exception
	do: [ :error | self errorHandler handleError: error ] ] in WorkingSession>>runList:do: in Block: [ :each | ...
Array(SequenceableCollection)>>do:
WorkingSession>>runList:do:
WorkingSession>>runStartup:
WorkingSession>>start:
SessionManager>>launchSnapshot:andQuit:
[ isImageStarting := self launchSnapshot: save andQuit: quit.
wait signal ] in SessionManager>>snapshot:andQuit: in Block: [ isImageStarting := self launchSnapshot: save and...etc...
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess in Block: [ self value....
Error: External module not found
ExternalLibraryFunction(Object)>>error:
ExternalLibraryFunction(Object)>>externalCallFailed
ExternalLibraryFunction(ExternalFunction)>>invokeWithArguments:
LGitLibrary>>libgit2_init
FFICalloutAPI>>function:library:
LGitLibrary(Object)>>ffiCall:library:options:
LGitLibrary(Object)>>ffiCall:library:
LGitLibrary(Object)>>ffiCall:
LGitLibrary>>libgit2_init
[ self libgit2_init.
self recordInitializationSuccess ] in LGitLibrary>>initializeLibGit2 in Block: [ self libgit2_init....
BlockClosure>>on:do:
LGitLibrary>>initializeLibGit2
LGitLibrary class>>startUp:
ClassSessionHandler>>startup:
[ :each | each startup: isImageStarting ] in WorkingSession>>runStartup: in Block: [ :each | each startup: isImageStarting ]
[ aBlock value: each ] in [ :each | 
[ aBlock value: each ]
	on: Exception
	do: [ :error | self errorHandler handleError: error ] ] in WorkingSession>>runList:do: in Block: [ aBlock value: each ]
BlockClosure>>on:do:
[ :each | 
[ aBlock value: each ]
	on: Exception
	do: [ :error | self errorHandler handleError: error ] ] in WorkingSession>>runList:do: in Block: [ :each | ...
Array(SequenceableCollection)>>do:
WorkingSession>>runList:do:
WorkingSession>>runStartup:
WorkingSession>>start:
SessionManager>>launchSnapshot:andQuit:
[ isImageStarting := self launchSnapshot: save andQuit: quit.
wait signal ] in SessionManager>>snapshot:andQuit: in Block: [ isImageStarting := self launchSnapshot: save and...etc...
[ self value.
Processor terminateActive ] in BlockClosure>>newProcess in Block: [ self value....
```
Because it's late at night and I'm getting lazy, I did setup the Ubuntu environment in pretty much the same way as the Fedora one. I didn't get the `libgit2` errors either in the terminal, Pharo Launcher, or in the Pharo 8.0 VM.

[0]  https://download.fedoraproject.org/pub/fedora/linux/releases/31/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-31-1.9.iso
[1]  https://getfedora.org/static/checksums/Fedora-Workstation-31-1.9-x86_64-CHECKSUM
[2]  https://getfedora.org/en/security/
[3]  https://files.pharo.org/pharo-launcher/linux64

<blockquote></blockquote>
<blockquote></blockquote>
<blockquote><img src="https://getfedora.org/static/images/fedora.png" width="48" align="right"><div><strong><a href="http://getfedora.org">Get Fedora</a></strong></div><div>Choose Freedom. Choose Fedora. Pick a flavor of Fedora streamlined for your needs, and get to work right away.</div></blockquote>
<blockquote></blockquote>

**Comment by Ducasse** [comment]
Thanks a lot for this great report. Christophe is working on it.

**Comment by a12l** [comment]
I would like to add that it's only the Pharo 8.0 64-bit and Pharo 7.0 64-bit that give me the error message. Pharo 6.1 doesn't give me a error message, neither is any of the 32-bit images.

**Comment by geruiz** [comment]
I had a similar error with Pharo 8 build 1134.  In my case the log was:

`ioLoadModule(//home/german/prog/pharo8.0/lib/pharo/5.0-202002121043/libgit2.so):
  libcurl-gnutls.so.4: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio
External module not found
ExternalLibraryFunction(Object)>>error:
ExternalLibraryFunction(Object)>>externalCallFailed
ExternalLibraryFunction(ExternalFunction)>>invokeWithArguments:
LGitLibrary>>libgit2_init
FFICalloutAPI>>function:library:`

I fixed it by installing the package libcurl4 (in opensuse linux) and creating a sym link to that file:

`ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4`

**Comment by demarey** [comment]
I updated Pharo Launcher to do not initialize libgit as it is only useful for development.
The problem should be solved

**Comment by amiracam** [comment]
interesting I did not encounter such issue on Ubuntu 18 LTS, I have git installed not sure about those particular libs, anyhow non-issue since its been resolved

**Comment by zoliky** [comment]
![error](https://user-images.githubusercontent.com/3882981/86558921-5790db00-bf63-11ea-98fd-350303e8c201.png)

It is still happening in Fedora 32. Any clue?

**Comment by zoliky** [comment]
The bug still exists.
Pharo 8.0 - 64bit (stable) on Fedora 32 Workstation.

When Pharo opens: 

![error](https://user-images.githubusercontent.com/3882981/86559263-341a6000-bf64-11ea-9b6d-7cede54ff045.png)

When I try to use Metacello, it fails with a similar error:

![b](https://user-images.githubusercontent.com/3882981/86559510-c4f13b80-bf64-11ea-9fc0-c69a97b7d953.png)

I installed Ubuntu 20.04 in Virtualbox and everything worked fine, no warnings and Metacello worked fine. In Fedora however the bug persists.

**Comment by zilti** [comment]
For me, `ln -s /usr/lib64/libcurl.so.4 /usr/lib64/libcurl-gnutls.so.4` did the trick

**Comment by ackerleytng** [comment]
I'm getting this error too, when launching the Pharo Mooc, Pharo 8.0

I'm on Arch: `Linux ackerleytng-computer 5.7.9-arch1-1 #1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64 GNU/Linux`

**Comment by zilti** [comment]
Tbf though I've given up on giving Pharo another try after a few years. It seems all sorts of broken. Even such basic things as opening the dialog to install libraries just completely crash it.

**Comment by kogiokka** [comment]
I've found a solution for Fedora 32, although I don't know how does it work.

Replacing `libgit2.so` in pharo-vm with the system one:
1. Install `libgit2.so.1.0` with `dnf install libgit2`
2.  `cp /usr/lib64/libgit2.so.1.0 ~/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so`

And there should be no error on the next launch.

Tested with `Pharo8.0.0 build: 1124, commit: 0932da8`

**Comment by geruiz** [comment]
@kogiokka I tried your solution and it works!!

Thanks a lot!

**Comment by ackerleytng** [comment]
I dug into this a little bit - I believe the correct solution is to install `libcurl-gnutls.so.4` systemwide.

I did this:

```
$ ldd ~/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so
ldd: warning: you do not have execution permission for `/home/ackerleytng/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so'
        linux-vdso.so.1 (0x00007ffff71fa000)
        libcurl-gnutls.so.4 => not found
        libz.so.1 => /usr/lib/libz.so.1 (0x00007fbb9172c000)
        libssl.so.1.0.0 => not found
        libcrypto.so.1.0.0 => not found
        libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007fbb916ec000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007fbb916e1000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fbb916bd000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007fbb914f6000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007fbb91466000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007fbb91189000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007fbb91ab9000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007fbb91183000)
```
Which shows that I have a few libraries missing. 

After installing `libcurl-gnutls` with

```
pacman -S libcurl-gnutls
```

I get this

```
$ ldd ~/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so
ldd: warning: you do not have execution permission for `/home/ackerleytng/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so'
/home/ackerleytng/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /home/ackerleytng/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so)
        linux-vdso.so.1 (0x00007ffdbb91a000)
        libcurl-gnutls.so.4 => /usr/lib/libcurl-gnutls.so.4 (0x00007f9e462c6000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f9e462ac000)
        libssl.so.1.0.0 => not found
        libcrypto.so.1.0.0 => not found
        libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007f9e4626c000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f9e46261000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f9e4623d000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f9e46076000)
        libnghttp2.so.14 => /usr/lib/libnghttp2.so.14 (0x00007f9e4604a000)
        libidn2.so.0 => /usr/lib/libidn2.so.0 (0x00007f9e46029000)
        libpsl.so.5 => /usr/lib/libpsl.so.5 (0x00007f9e46016000)
        libnettle.so.8 => /usr/lib/libnettle.so.8 (0x00007f9e45fd8000)
        libgnutls.so.30 => /usr/lib/libgnutls.so.30 (0x00007f9e45e0f000)
        libssl.so.1.1 => /usr/lib/libssl.so.1.1 (0x00007f9e45d7f000)
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1 (0x00007f9e45aa2000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f9e466c1000)
        libunistring.so.2 => /usr/lib/libunistring.so.2 (0x00007f9e45920000)
        libp11-kit.so.0 => /usr/lib/libp11-kit.so.0 (0x00007f9e457f7000)
        libtasn1.so.6 => /usr/lib/libtasn1.so.6 (0x00007f9e457df000)
        libhogweed.so.6 => /usr/lib/libhogweed.so.6 (0x00007f9e45797000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f9e456f6000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f9e456f0000)
        libffi.so.7 => /usr/lib/libffi.so.7 (0x00007f9e456e4000)
```

And the Pharo Mooc image starts up without the error.

I'm not sure what the goals of the pharo-launcher are, but if we want to provide a smooth experience, it might make sense to package `libcurl-gnutls.so.4` in, or otherwise improve error messages!

I would like to help out! I'm new to Pharo and would appreciate pointers.

**Comment by zoliky** [comment]
> I've found a solution for Fedora 32, although I don't know how does it work.
> 
> Replacing `libgit2.so` in pharo-vm with the system one:
> 
> 1. Install `libgit2.so.1.0` with `dnf install libgit2`
> 2. `cp /usr/lib64/libgit2.so.1.0 ~/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so`
> 
> And there should be no error on the next launch.
> 
> Tested with `Pharo8.0.0 build: 1124, commit: 0932da8`

It works. Thanks.

**Comment by arcanosam** [comment]
I am beta testing Pharo Fun Mooc on a machine with Fedora 32 and I didn't have this problem.

I switch for another machine with Fedora 32 too and this problem shows up.

I did the ldd command like @ackerleytng says:

ldd: warning: you do not have execution permission for `~/Pharo/vms/80-x64/lib/pharo/5.0-202002121043/libgit2.so'
        linux-vdso.so.1 (0x00007fff86af5000)
        libcurl-gnutls.so.4 => not found
        libz.so.1 => /lib64/libz.so.1 (0x00007f318d340000)
        libssl.so.1.0.0 => not found
        libcrypto.so.1.0.0 => not found
        libssh2.so.1 => /lib64/libssh2.so.1 (0x00007f318d2fe000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f318d2f3000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f318d2cf000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f318d105000)
        libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f318d06e000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f318cd81000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f318d6c6000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f318cd7a000)

To solve I opted to use the symlink as @zilti did and because I found this link too https://steamcommunity.com/app/269210/discussions/0/1740012252799388820/

The initial error not show anymore and I could use Iceberg without problem.

Thanks all.


<blockquote><img src="https://steamcdn-a.akamaihd.net/steam/apps/269210/header.jpg?t=1595337793" width="48" align="right"><div><strong><a href="https://steamcommunity.com/app/269210/discussions/0/1740012252799388820/">Game missing libcurl-gnutls.so.4 (Linux) :: Hero Siege General Discussions</a></strong></div><div>I'm running Slackware Linux, used to play this over a year ago without issues. I just reinstalled the game to see how it's changed, but nothing launches clicking "Play" in steam. If i do to the common/HeroSiege/linux directory and launch the game binary directly, all i get is this: $ ./Hero_Siege ./Hero_Siege: error while loading shared libraries: libcurl-gnutls.so.4: cannot open shared object file: No such file or directory However, i do have the steam-runtime library on my system; $ locate...</div></blockquote>

**Comment by Xfireball8** [comment]
This problem exists on CentOS 8 with Pharo 9 64 bits, the steps to reproduce the bug is the same as the original post.

The problem was resolved by copying libgit2 from /usr/lib64/libgit2.so to the images library repository (~/Pharo/images/90-x64/lib/libgit2.1.0.0.so)
