### ISSUE TITLE
WeakValueDictionary has race condition issues

### ISSUE THREAD

**Issue by dionisiydk** [guillep/pharo-core#4487]
During review of #4421 I found that method #associationsDo: can pass nil value of GC-ed item to the new strong Association for enumeration block.
Most of collection API is relying on this method in dictionary implementation. So potentially users of those methods could break due to unexpected nil values:
```Smalltalk
WeakValueDictionary>>associationsDo: aBlock
	"Evaluate aBlock for each of the receiver's elements (key/value associations)."

	tally = 0 ifTrue: [ ^ self ].
	array do: [ :each | each value ifNotNil: [ aBlock value: each key -> each value enclosedSetElement ] ]
```
Here the garbage collection can happen just after "each value ifNotNil:" and following new call to #value can return nil if actual value is being GC-ed.

For the fix we should simply use the argument of ifNotNil: block as an association value.

**Comment by jecisc** [comment]
I agree!

**Comment by jecisc** [comment]
@dionisiydk I checked and apparently, I already did it in 319986092702d0613a3a79b577c7f9570e428bd5

**Comment by dionisiydk** [comment]
Right. I should first check the latest image.
But looking in similar places I think the #valuesDo is not safe:
```Smalltalk
valuesDo: aBlock
	"See comments in Dictionary>>valuesDo:.  The code keeps
	a reference to the value to facilitate debugging"

	tally = 0 ifTrue: [ ^ self ].
	1 to: array size do: [ :eachIndex | 
		| eachAssociation eachValue |
		eachAssociation := array at: eachIndex.
		nil == eachAssociation value
			ifFalse: [ eachValue := eachAssociation value enclosedElement.
				aBlock value: eachValue ] ]
``` 
The last #value here could return nil in the case of GC. It should be:
```Smalltalk
eachValue := eachAssociation value.
eachValue ifNotNil: [aBlock value: eachValue enclosedElement]
```

**Comment by jecisc** [comment]
This one I fixed it in ed09e83529460a7646a55348db39b6cca6441223

**Comment by dionisiydk** [comment]
Thanks @jecisc . And sorry for noise. 
(still not on latest version)

**Comment by jecisc** [comment]
No problem! I prefer false positives than false negatives while looking for race conditions ;)
