### ISSUE TITLE
Add executable comments in SequenceableCollection - sorting shuffling split protocol

### ISSUE THREAD

**Issue by Ducasse** [guillep/pharo-core#5450]
There are a lot of opportunities to improve the comment using executable comments in the collection hierarchy and in particular SequencableCollection 

"#(a b c) allButFirst >>> #(b c)"

**Comment by juliendelplanque** [comment]
Looks like it was fixed in #5461 so we can close it?

**Comment by LaurineDargaud** [comment]
There are no executable comments, so the issue is still valid.
