### ISSUE TITLE
Step to return requires explicit debugger step

### ISSUE THREAD

**Issue by pavel-krivanek** [guillep/pharo-core#8166]
**Bug description**
When you install a breakpoint or do `self halt`, the `Step to return` context menu action in the debugger ends on the same place where the breakpoint is installed. 

**To Reproduce**
1. create and run following method:
``` smalltalk
message 

	| var | 
	
	self halt.
	var := self class environment allClasses.
	var := var reversed.
	^ var
```
2. In the debugger, do `Step to return` from the context menu. The debugger will change state to `Halt in TstClass(Object)>>halt`

It works as expected when you do a single step (through) before _step to return_.

**Comment by StevenCostiou** [comment]
I cannot reproduce it. Is this fixed now?
Normally if you encounter any exception it should stop (there I have a bug, it opens dead debuggers), but halts and breaks are kinda special. 
I guess it does make sense to go over them while explicitly stepping to the return, but I cannot reproduce your bug.
I am adding additional tests to check that.

**Comment by StevenCostiou** [comment]
Hmm even with breakpoints it works as expected. I guess it was fixed sicne this issue is a bit old now :/

**Comment by StevenCostiou** [comment]
So maybe it was fixed somehow since then, but I cannot reproduce with your example.
In any case, I improved the step to return:

```Smalltalk
stepToReturn

	[ 
	self context willReturn or: [ self hasSignalledUnhandledException ] ] 
		whileFalse: [ self debugSession stepOver ]
```

and this test passes:

```Smalltalk
testStepToReturnWithHalt
	| dbg |
	"First return node"
	dbg := SindarinDebugger debug: [ self helperMethodReturnWithHalt ].
	dbg stepToMethodEntry.
	dbg stepToReturn.
	
	self assert: dbg context willReturn.
	self assert: dbg node parent isReturn.
	self assert: dbg topStack equals: 1
```

The helper method is:

```Smalltalk
helperMethodReturnWithHalt
	| a |
	a := 0.
	self halt.
	^ a + 1
```

Once this is merged, I will indicate in this issue and if you could let me know if it now works as expected it would be great ;)

**Comment by pavel-krivanek** [comment]
I took P9 1025, loaded NewTools and I can still reproduce it:

![e4hIyfg97U](https://user-images.githubusercontent.com/572494/103887454-580d5880-50e3-11eb-935b-b4947a3db2fe.gif)

**Comment by StevenCostiou** [comment]
Ok I can reproduce it now, and it freezes my image if I step just after.
Thank you I will fix that.
