### ISSUE TITLE
Cmd-g on an erroneous code does not open a debugger

### ISSUE THREAD

**Issue by bergel** [guillep/pharo-core#8671]
**Describe the bug**
Consider a piece of code that raises an exception (e.g., `1 / 0`). Evaluating the code in a playground using `Cmd-g` does not open a debugger. Instead, it show a not-so-useful little red window.

**To Reproduce**
1. Open a playground
2. type `1 / 0`
3. Press Cmd-g

**Expected behavior**
I would expect a debugger to open

**Screenshots**
![image](https://user-images.githubusercontent.com/393742/109501538-01dfe480-7a98-11eb-8d52-f1119ff84959.png)

**Version information:**
 - macOS 
 - Pharo 9, bleeding edge.

**Expected development cost**
Should not be too hard to fix I guess

**Comment by Ducasse** [comment]
I think that Esteban did it on purpose so we should discuss it.

**Comment by estebanlm** [comment]
nah, that's definitively a bug :)

**Comment by MarcusDenker** [comment]
I think this is fixed by https://github.com/pharo-project/pharo/pull/8796

**Comment by bergel** [comment]
I have tried in a new P9 image and I still see it:
<img width="866" alt="image" src="https://user-images.githubusercontent.com/393742/111644839-7dfc5b00-8800-11eb-9151-72f2b7a78d12.png">

But maybe it was fixed and not available within the launcher... No idea.

**Comment by MarcusDenker** [comment]
It was just merged... will take some time for the build

**Comment by MarcusDenker** [comment]
I now get a DNU for #evaluate:ifError: on SpCodePresenter

**Comment by MarcusDenker** [comment]
fixes by https://github.com/pharo-project/pharo/pull/8826
